
language: node_js

node_js:
    - "stable"
    - "12"
    - "10"
    - "8"

script:
    - >
      nodeVersionMajor=`node -e "console.log(process.versions.node.split('.')[0])"`;

      if [ $nodeVersionMajor -eq 12 ]; then
        npm run lint;
      else
        echo "*** Do not lint for non node.js 12 builds ($nodeVersionMajor)";
      fi;

    - >
      nodeVersionMajor=`node -e "console.log(process.versions.node.split('.')[0])"`;

      if [ $nodeVersionMajor -gt 4 ]; then
        npm test;
      else
        npm run testWithNode;
      fi;

    - >
      nodeVersionMajor=`node -e "console.log(process.versions.node.split('.')[0])"`;

      if [ $nodeVersionMajor -eq 12 ]; then
        npm run makeCodeCoverageSummaryReport;
        npm run makeCodeCoverageDetailReport;
        coveralls < coverage/lcov.info;
      else
        echo "*** Do not make coverage reports for non node.js 12 builds ($nodeVersionMajor)";
      fi;
