
language: node_js

node_js:
    - "stable"
    - "8"
    - "6"
    - "4"

script:
    - >
      npmVersionMajor=`npm --version | grep -Eo '^[0-9]+'`;

      if [ $npmVersionMajor -ge 6 ]; then
        npm audit;
      else
        echo "Do not run \`npm audit\` for npm < 6 ($npmVersionMajor)";
      fi;

    - npm run lint

    - npm test
